### ISSUE TITLE
Convert Travis build to Github actions.

### ISSUE THREAD

**Issue by evilsocket** [bettercap/bettercap#1114]
When a new release is tagged, a Travis build was supposed to [create and upload precompiled binaries](https://github.com/bettercap/bettercap/blob/master/.travis.yml), including macOS and Windows ones. Travis removed the free plan so this is no longer possible.

The .travis.yml file must be converted to a github action which includes the builds for Windows and macOS, I have no idea how to do it.

This is a requirement before I can tag a new release, halp!

**Comment by evilsocket** [comment]
omg thank you so much @MelroyB! will test

**Comment by evilsocket** [comment]
sadly [this is not working](https://github.com/bettercap/bettercap/actions/runs/10316919919/job/28560113485) ... i don't think we need to use arm_builder anymore

**Comment by MelroyB** [comment]
I am not an expert at this, but maybe this works?

```
name: Build and Test

on:
  push:
    tags:
      - 'v*.*.*'    # Match version tags

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.16.x']
        include:
          - os: ubuntu-latest
            arch: amd64
            target_os: linux
            target_arch: amd64
          - os: ubuntu-latest
            arch: arm64
            target_os: linux
            target_arch: aarch64
          - os: ubuntu-latest
            arch: amd64
            target_os: linux
            target_arch: armhf
            cross_build: true
          - os: macos-latest
            arch: amd64
            target_os: darwin
            target_arch: amd64
          - os: windows-latest
            arch: amd64
            target_os: windows
            target_arch: amd64
            output: bettercap.exe

    env:
      TARGET_OS: ${{ matrix.target_os }}
      TARGET_ARCH: ${{ matrix.target_arch }}
      GO_VERSION: ${{ matrix.go-version }}
      OUTPUT: ${{ matrix.output || 'bettercap' }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y p7zip-full libpcap-dev libnetfilter-queue-dev libusb-1.0-0-dev

    - name: Install Dependencies on macOS
      if: runner.os == 'macOS'
      run: brew install libpcap libusb p7zip

    - name: Install Dependencies on Windows
      if: runner.os == 'Windows'
      run: |
        choco install openssl.light -y
        choco install make -y
        choco install 7zip -y
        choco install pkgconfiglite -y
        mkdir C:\pkg-config
        choco install zadig -y
        curl -L "https://github.com/libusb/libusb/releases/download/v1.0.24/libusb-1.0.24.7z" -o "C:\libusb.7z"
        7z x -y "C:\libusb.7z" -o"C:\libusb"
        curl -L "https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip" -o "C:\wpcap-sdk.zip"
        7z x -y "C:\wpcap-sdk.zip" -o"C:\winpcap"
        cp builder\libusb.pc C:\pkg-config\libusb.pc
        cp builder\libusb.pc C:\pkg-config\libusb-1.0.pc

    - name: Install QEMU for Cross Compilation (Linux only)
      if: matrix.cross_build && runner.os == 'Linux'
      run: |
        wget --show-progress -qcO "qemu.deb" "https://github.com/bettercap/buildutils/raw/main/qemu-user-static_5.2_dfsg-9_amd64.deb"
        sudo dpkg -i "qemu.deb"

    - name: Build
      run: |
        if [ -n "${{matrix.cross_build}}" ]; then
          sudo builder/arm_builder.sh bettercap make -e TARGET="${{ env.OUTPUT }}"
        else
          make -e TARGET="${{ env.OUTPUT }}"
        fi

    - name: Verify Build
      run: |
        file "${{ env.OUTPUT }}"
        openssl dgst -sha256 "${{ env.OUTPUT }}" | tee bettercap_${{ matrix.target_os }}_${{ matrix.target_arch }}_${{ env.VERSION }}.sha256
        7z a "bettercap_${{ matrix.target_os }}_${{ matrix.target_arch }}_${{ env.VERSION }}.zip" "${{ env.OUTPUT }}" "bettercap_${{ matrix.target_os }}_${{ matrix.target_arch }}_${{ env.VERSION }}.sha256"
        ls -la bettercap*

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: ['1.16.x']

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y p7zip-full libpcap-dev libnetfilter-queue-dev libusb-1.0-0-dev

    - name: Install Dependencies on macOS
      if: runner.os == 'macOS'
      run: brew install libpcap libusb p7zip

    - name: Run Tests
      run: |
        env GO111MODULE=on make test

# Deployment is triggered on push of version tags and the files are already zipped and hashed during the build job.
deploy:
  needs: [build]
  if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
  name: Release
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bettercap_*.zip
          bettercap_*.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
**Changes Made:**
- Updated Dependency Installation: Used conditional steps to install the required dependencies depending on the OS.
- Updated Actions Versions: Updated actions/checkout to v3 and actions/setup-go to v4 to address the Node.js deprecation warnings.
- Fixed Potential Cross-Build Issues: Ensured that the sudo builder/arm_builder.sh is only called when cross-building on Linux.
